# script to generate fake data for reproduction number analaysis


# currently data just chooses random times for infection events but could easily be modified
# to model infections being generated by other people

# 1. Infectious_people - dataframe where each row corresponds to one infectious person on one day
# (i.e. so there is one record for each day there is an infectious person):
#   fields:
#   
#   personID  - unique id for person
# person_type - eg. Community-acquired, Nosocomial, HCW
# 
# Date       - eg. integer for day of study
# Relative_infectiousness - a number proportional to daily risk of transmission to a susceptible exposed to this person 
# (e.g. based on viral shedding data or on ).
# Ward_ID - what ward patient is on on a given day (assume at most one ward per day, so if more than one take ward where most time was spent)


create_infectious_people<-function(num.communityacquired.patients=100, num.hospitalacquired.patients=50, meanlos=7, numHCWs=20, maxday=100, numwards=2){
  #creates fake data in dataframe Infectious_people with given number of patients from day 1 up to maxday
  rownum<-1

  Infectious_people<-data.frame(personID=NA, person_type=NA, date=NA,Relative_infectiousness=NA, Ward_ID=NA)
  # for person_type 1 = community acquired patients; 2=hospital acquired patients, 3= HCWs
  personID<-0
  # create communityacquired patients
  for(i in 1:num.communityacquired.patients){
    personID<-personID + 1
    # choose ward  (at random for now)
    Ward_ID<-ceiling(runif(1,min=0,max=numwards))
    # choose date wgen first infectious
    day.first.infectious<-round(runif(n=1,min=1, max=maxday))
    duration.of.infectiousness<-5 # for now take this be constant, but in general it could be sampled from a distribution 
    daytomakeinfectious<-day.first.infectious
    day.of.infection<-1
    while(daytomakeinfectious<=maxday & day.of.infection<=duration.of.infectiousness){
      # make infectious on this day
      Infectious_people[rownum,] <-NA
      Infectious_people$personID[rownum]<-personID
      Infectious_people$person_type[rownum]<-1
      Infectious_people$date[rownum]<-daytomakeinfectious
      Infectious_people$Relative_infectiousness[rownum] <-1 # later can modify this to allow infectious profile to change
      Infectious_people$Ward_ID[rownum]<-Ward_ID
      daytomakeinfectious<-daytomakeinfectious +1
      day.of.infection<-day.of.infection +1
      rownum<-rownum+1
    }    
  }
  
  # create hospital acquired patients
  for(i in 1:num.hospitalacquired.patients){
    personID<-personID + 1
    Ward_ID<-ceiling(runif(1,min=0,max=numwards))
    
    # choose date wen first infectious
    day.first.infectious<-round(runif(n=1,min=1, max=maxday))
    duration.of.infectiousness<-7 # for now take this be constant, but in general it could be sampled from a distribution 
    daytomakeinfectious<-day.first.infectious
    day.of.infection<-1
    while(daytomakeinfectious<=maxday & day.of.infection<=duration.of.infectiousness){
      # make infectious on this day
      Infectious_people[rownum,] <-NA
      Infectious_people$personID[rownum]<-personID
      Infectious_people$person_type[rownum]<-2
      Infectious_people$date[rownum]<-daytomakeinfectious
      Infectious_people$Relative_infectiousness[rownum] <-1 # later can modify this to allow infectious profile to change
      Infectious_people$Ward_ID[rownum]<-Ward_ID
      daytomakeinfectious<-daytomakeinfectious +1
      day.of.infection<-day.of.infection +1
      rownum<-rownum+1
    }    
  }
    # create infected HCWs
  for(i in 1:numHCWs){
      personID<-personID + 1
      Ward_ID<-ceiling(runif(1,min=0,max=numwards))
      # choose date wen first infectious
      day.first.infectious<-round(runif(n=1,min=1, max=maxday))
      duration.of.infectiousness<-2 # for now take this be constant, but in general it could be sampled from a distribution 
      daytomakeinfectious<-day.first.infectious
      day.of.infection<-1
      while(daytomakeinfectious<=maxday & day.of.infection<=duration.of.infectiousness){
        # make infectious on this day
        Infectious_people[rownum,] <-NA
        Infectious_people$personID[rownum]<-personID
        Infectious_people$person_type[rownum]<-3
        Infectious_people$date[rownum]<-daytomakeinfectious
        Infectious_people$Relative_infectiousness[rownum] <-1 # later can modify this to allow infectious profile to change
        Infectious_people$Ward_ID[rownum]<-Ward_ID
        daytomakeinfectious<-daytomakeinfectious +1
        day.of.infection<-day.of.infection +1
        rownum<-rownum+1
      }    
  }
  
  return(Infectious_people)
}

# 2. Infected_patients - dataframe of patients  who became infected while in the hospital (according to assumed definition of nosocomial infections)
# 
# fields:
#   
#   personID  - unique id for person
# person_type - eg. Community-acquired, Nosocomial, HCW
# Date_onset       - date of symptom onset (from data)
# Date_infection       - date of first infection (imputed - will need to create multiple data frames with different dates )
# Date_of_admission - date of first admission. 

# derive these from Infectious_people data frame (people of type 2). 
# assuming an incubation period 




create_infected_patients<-function(Infectious_people, incubation_period=3){
  #function takes two argument, the dataframe of infectious people and incubation period, and returns data frame of infection events
  # we consider only people of person_type =2 
  # the we select the records representing first day of infection
  temp<-Infectious_people[Infectious_people$person_type==2,]
  first.day.inectious<-tapply(temp$date, temp$personID,min) #names give patient ID values give first day infectious
  Infected_patients<-data.frame(personID=as.integer(names(first.day.inectious)), person_type=2,Date_onset= as.integer(first.day.inectious))
  Infected_patients$Date_infection <-Infected_patients$Date_onset-incubation_period
  Infected_patients$Ward_ID<- Infectious_people$Ward_ID[match(Infected_patients$personID, Infectious_people$personID)]
  return(Infected_patients)
}


create_infected_hcws<-function(Infectious_people, incubation_period=3){
  #function takes two argument, the dataframe of infectious people and incubation period, and returns data frame of infection events
  # we consider only people of person_type =3 
  # the we select the records representing first day of infection
  temp<-Infectious_people[Infectious_people$person_type==3,]
  first.day.inectious<-tapply(temp$date, temp$personID,min) #names give patient ID values give first day infectious
  Infected_hcws<-data.frame(personID=as.integer(names(first.day.inectious)), person_type=3,Date_onset= as.integer(first.day.inectious))
  Infected_hcws$Date_infection <-Infected_hcws$Date_onset-incubation_period
  Infected_hcws$Ward_ID<- Infectious_people$Ward_ID[match(Infected_hcws$personID, Infectious_people$personID)]
  
  return(Infected_hcws)
}

  

Infectious_people<-create_infectious_people()
Infected_patients<-create_infected_patients(Infectious_people)
Infected_staff<-create_infected_hcws(Infectious_people)
